### ISSUE TITLE
Can't set phonePickerDelegate Programatically

### ISSUE THREAD

**Issue by ibrahimchiha** [NikKovIos/NKVPhonePicker#1]
I believe there is no way to set the phonePickerDelegate as it's not an option while using the picker programmatically. Or I haven't figured out the way.

**Comment by NikKovIos** [comment]
You're right - it has been already fixed and would be in next release.  
You can use `pod 'NKVPhonePicker', :git => 'https://github.com/NikKovIos/NKVPhonePicker/'` until this update would be in cocoapods repo.

**Comment by ibrahimchiha** [comment]
It should be set to UIViewController or UITextFieldDelegate? Cause I don't see the NKVPhonePickerTextViewDelegate as an option??

**Comment by NikKovIos** [comment]
/// Set this property in order to present the CountryPickerViewController
    /// when user clicks on the flag button
    @IBOutlet public weak var phonePickerDelegate: UIViewController?

**Comment by ibrahimchiha** [comment]
<img width="553" alt="screen shot 2017-05-31 at 9 57 19 pm" src="https://cloud.githubusercontent.com/assets/12511453/26648744/2814d2ca-464c-11e7-877e-8646d0a41600.png">
That's why I did, but it still doesn't work. There seems to be some other bug

**Comment by NikKovIos** [comment]
Copy code as text please. Also write exactly, what is not working?

**Comment by ibrahimchiha** [comment]
lazy var phoneTextField: NKVPhonePickerTextField = {
        let textField = NKVPhonePickerTextField()
        textField.placeholder = "ex: 03123456"
        textField.autocorrectionType = .no
        textField.phonePickerDelegate = self
        textField.keyboardType = .numberPad
        textField.favoriteCountriesLocaleIdentifiers = ["LB"]
        textField.layer.borderWidth = 1
        textField.layer.borderColor = UIColor.customBlue().cgColor
        textField.layer.cornerRadius = 5
        textField.font = UIFont.boldSystemFont(ofSize: 18)
        textField.textColor = UIColor.customGray()
        textField.translatesAutoresizingMaskIntoConstraints = false
        return textField
    }()

This is the code. When I tap on the country flag, the textField resigns first responder but the Country Picker View never shows up.

**Comment by NikKovIos** [comment]
Try now.  
`pod 'NKVPhonePicker', :git => 'https://github.com/NikKovIos/NKVPhonePicker/'`

**Comment by ibrahimchiha** [comment]
Nothing changed? It still doesn't show the Country Picker.

**Comment by NikKovIos** [comment]
I've also update an example, check the difference between it and your code please.

**Comment by ibrahimchiha** [comment]
There's a bug in this pod:
pod 'NKVPhonePicker', :git => 'https://github.com/NikKovIos/NKVPhonePicker/'

After I copied the files manually from your Example Project everything worked fine.

**Comment by NikKovIos** [comment]
It seems, that you didn't update pod and just called pod install again.
